# Generated by Django 4.2 on 2024-09-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
