version: '3.3'

services:
  d09:
    container_name: d09
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/d09:/d09
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8080:80"
    restart: always

volumes:
  pg_data:
