# Generated by Django 3.2.25 on 2024-08-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='created',
        ),
        migrations.RemoveField(
            model_name='people',
            name='updated',
        ),
    ]
